### ISSUE TITLE
EdDSA signed Key Binding JWT verification fails

### ISSUE THREAD

**Issue by nemqe** [eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt#245]
Hello,

When issuing a credential that has a `cnf.jwk` of an OKP key type and signing the Key Binding JWT with that key the verification of the presentation fails.

I tracked this to the fact that the Nimbus `OctetKeyPair` [does not support the `toPublicKey()`](https://bitbucket.org/connect2id/nimbus-jose-jwt/src/6020cd17c747bf7bc7d3f6a022daacec2fa52344/src/main/java/com/nimbusds/jose/jwk/OctetKeyPair.java#lines-896) call, i.e. it throws a `JOSEException("Export to java.security.PrivateKey not supported");`

I found the call to `toPublicKey()` in the `NimbusIntegration.KeyBindingVerifier.Companion.mustBePresentAndValid` function.

Stack trace:

```
Caused by: com.nimbusds.jose.JOSEException: Export to java.security.PublicKey not supported
	at com.nimbusds.jose.jwk.OctetKeyPair.toPublicKey(OctetKeyPair.java:899) ~[nimbus-jose-jwt-9.39.3.jar:9.39.3]
	at eu.europa.ec.eudi.sdjwt.NimbusIntegrationKt$mustBePresentAndValid$keyBindingVerifierProvider$1.invoke(NimbusIntegration.kt:93) ~[eudi-lib-jvm-sdjwt-kt-0.6.4.jar:0.6.4]
	at eu.europa.ec.eudi.sdjwt.NimbusIntegrationKt$mustBePresentAndValid$keyBindingVerifierProvider$1.invoke(NimbusIntegration.kt:91) ~[eudi-lib-jvm-sdjwt-kt-0.6.4.jar:0.6.4]
	at eu.europa.ec.eudi.sdjwt.KeyBindingVerifier$DefaultImpls.verify_AOPTCDM$lambda$2$mustBePresentAndValid(SdJwtVerifier.kt:187) ~[eudi-lib-jvm-sdjwt-kt-0.6.4.jar:0.6.4]
	at eu.europa.ec.eudi.sdjwt.KeyBindingVerifier$DefaultImpls.verify-AOPTCDM(SdJwtVerifier.kt:201) ~[eudi-lib-jvm-sdjwt-kt-0.6.4.jar:0.6.4]
	at eu.europa.ec.eudi.sdjwt.KeyBindingVerifier$MustBePresentAndValid.verify-AOPTCDM(SdJwtVerifier.kt:219) ~[eudi-lib-jvm-sdjwt-kt-0.6.4.jar:0.6.4]
	at eu.europa.ec.eudi.sdjwt.SdJwtVerifier.verifyPresentation-BWLJW6A(SdJwtVerifier.kt:347) ~[eudi-lib-jvm-sdjwt-kt-0.6.4.jar:0.6.4]
	... X common frames omitted
```

I just wanted to see with you if this is something you want to support and discuss who can do the PR.

Thanks

**Comment by babisRoutis** [comment]
Hi @nemqe 

For a moment I though you were reporting again #229 :smile: 

A starting point to support this, would be 
https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/blob/88d2218e012ea1ef0d0e70ad2fc83ffba78d5f3b/src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt#L87

To be more precise, I think that there could be a similar method, specific  to `EdDSA`. The new method would use instead of `DefaultJWTProcessor` a customized version similar to [SdJwtVcJwtProcessor](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/blob/main/src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcJwtProcessor.kt), which delegates to `Ed25519Verifier` without calling `.toPublic()`

With regards to a PR, I will come back to you again. 
To be frank, library's next milestone is to support Type Metadata for SD-JWT-VC. 
If you implement something similar to the above (or better :) ) will be happy to review it.

**Comment by nemqe** [comment]
@dzarras Seems to be working

thanks for the quick fix, we were discussing today when we are going to do a PR but you beat us to it.
